use std::{collections::HashSet, fmt::Write};

use serde_json::{Error, Value, from_str};

const INITIALISMS: &[&str] = &[
    "ACL", "API", "ASCII", "CPU", "CSS", "DNS", "EOF", "GUID", "HTML", "HTTP", "HTTPS", "ID", "IP",
    "JSON", "LHS", "QPS", "RAM", "RHS", "RPC", "SLA", "SMTP", "SQL", "SSH", "TCP", "TLS", "TTL",
    "UDP", "UI", "UID", "UUID", "URI", "URL", "UTF8", "VM", "XML", "XMPP", "XSRF", "XSS",
];

#[derive(Clone, Debug)]
pub struct Options {
    pub type_name: Option<String>,
    pub flatten: bool,
    pub example: bool,
    pub all_omitempty: bool,
}

impl Default for Options {
    fn default() -> Self {
        Self {
            type_name: None,
            flatten: true,
            example: false,
            all_omitempty: false,
        }
    }
}

#[derive(Clone, Debug, PartialEq)]
enum Kind {
    String,
    Int,
    Int64,
    Float64,
    Bool,
    Time,
    Any,
    Array(Box<Kind>),
    Object(Vec<Field>),
}

#[derive(Clone, Debug, PartialEq)]
struct Field {
    json_name: String,
    kind: Kind,
    optional: bool,
    example: Option<String>,
}

pub fn convert(json: &str, options: &Options) -> Result<String, Error> {
    let value: Value = from_str(json)?;
    let root_name = format_identifier(options.type_name.as_deref().unwrap_or("AutoGenerated"));
    let root = infer(&value);
    let mut emitter = Emitter::new(options);
    let mut output = match root {
        Kind::Object(fields) => emitter.emit_root(&root_name, &fields),
        other => {
            let item_name = format!("{root_name}Item");
            format!("type {root_name} {}", emitter.type_expr(&other, &item_name, 0))
        }
    };
    if options.flatten {
        for definition in emitter.definitions {
            output.push_str("\n\n");
            output.push_str(&definition);
        }
    }
    output.push('\n');
    Ok(output)
}

fn infer(value: &Value) -> Kind {
    match value {
        Value::Null => Kind::Any,
        Value::Bool(_) => Kind::Bool,
        Value::Number(n) if n.is_i64() || n.is_u64() => match n.as_i64() {
            Some(v) if v > i64::from(i32::MIN) && v < i64::from(i32::MAX) => Kind::Int,
            _ => Kind::Int64,
        },
        Value::Number(_) => Kind::Float64,
        Value::String(s) if is_rfc3339_shape(s) => Kind::Time,
        Value::String(_) => Kind::String,
        Value::Array(values) => {
            let kind = values.iter().map(infer).reduce(merge_kinds).unwrap_or(Kind::Any);
            Kind::Array(Box::new(kind))
        }
        Value::Object(map) => Kind::Object(
            map.iter()
                .map(|(json_name, value)| Field {
                    json_name: json_name.clone(),
                    kind: infer(value),
                    optional: false,
                    example: scalar_example(value),
                })
                .collect(),
        ),
    }
}

fn merge_kinds(a: Kind, b: Kind) -> Kind {
    if a == b {
        return a;
    }
    match (a, b) {
        (Kind::Int, Kind::Int64) | (Kind::Int64, Kind::Int) => Kind::Int64,
        (Kind::Int | Kind::Int64, Kind::Float64) | (Kind::Float64, Kind::Int | Kind::Int64) => {
            Kind::Float64
        }
        (Kind::Array(a), Kind::Array(b)) => Kind::Array(Box::new(merge_kinds(*a, *b))),
        (Kind::Object(a), Kind::Object(b)) => Kind::Object(merge_fields(a, b)),
        _ => Kind::Any,
    }
}

fn merge_fields(mut a: Vec<Field>, b: Vec<Field>) -> Vec<Field> {
    for field in &mut a {
        if let Some(other) = b.iter().find(|f| f.json_name == field.json_name) {
            field.kind = merge_kinds(field.kind.clone(), other.kind.clone());
            field.optional |= other.optional;
        } else {
            field.optional = true;
        }
    }
    for mut field in b {
        if !a.iter().any(|f| f.json_name == field.json_name) {
            field.optional = true;
            a.push(field);
        }
    }
    a
}

fn scalar_example(value: &Value) -> Option<String> {
    match value {
        Value::String(s) if !s.is_empty() => Some(s.clone()),
        Value::Number(n) => Some(n.to_string()),
        Value::Bool(b) => Some(b.to_string()),
        _ => None,
    }
}

struct Emitter<'a> {
    options: &'a Options,
    definitions: Vec<String>,
    names: HashSet<String>,
}

impl<'a> Emitter<'a> {
    fn new(options: &'a Options) -> Self {
        Self {
            options,
            definitions: Vec::new(),
            names: HashSet::new(),
        }
    }

    fn emit_root(&mut self, name: &str, fields: &[Field]) -> String {
        format!("type {name} {}", self.struct_expr(fields, 0))
    }

    fn struct_expr(&mut self, fields: &[Field], indent: usize) -> String {
        let mut out = String::from("struct {\n");
        let mut field_names = HashSet::new();
        for field in fields {
            let base = format_identifier(&field.json_name);
            let name = unique_name(&base, &mut field_names);
            let type_name = matches!(field.kind, Kind::Object(_) | Kind::Array(_))
                .then(|| self.unique_type_name(&base))
                .unwrap_or(base);
            let typ = self.type_expr(&field.kind, &type_name, indent + 1);
            write!(
                out,
                "{}{name} {typ} `json:\"{}",
                "\t".repeat(indent + 1),
                escape_tag(&field.json_name)
            )
            .unwrap();
            if self.options.all_omitempty || field.optional {
                out.push_str(",omitempty");
            }
            out.push('"');
            if let (true, Some(example)) = (self.options.example, &field.example) {
                write!(out, " example:\"{}\"", escape_tag(example)).unwrap();
            }
            out.push_str("`\n");
        }
        write!(out, "{}}}", "\t".repeat(indent)).unwrap();
        out
    }

    fn type_expr(&mut self, kind: &Kind, suggested: &str, indent: usize) -> String {
        match kind {
            Kind::String => "string".into(),
            Kind::Int => "int".into(),
            Kind::Int64 => "int64".into(),
            Kind::Float64 => "float64".into(),
            Kind::Bool => "bool".into(),
            Kind::Time => "time.Time".into(),
            Kind::Any => "any".into(),
            Kind::Array(inner) => format!("[]{}", self.type_expr(inner, suggested, indent)),
            Kind::Object(fields) if self.options.flatten => {
                let definition = format!("type {suggested} {}", self.struct_expr(fields, 0));
                self.definitions.push(definition);
                suggested.to_string()
            }
            Kind::Object(fields) => self.struct_expr(fields, indent),
        }
    }

    fn unique_type_name(&mut self, base: &str) -> String {
        unique_name(base, &mut self.names)
    }
}

fn unique_name(base: &str, seen: &mut HashSet<String>) -> String {
    if seen.insert(base.to_string()) {
        return base.to_string();
    }
    let mut n = 0;
    loop {
        let candidate = format!("{base}{n}");
        if seen.insert(candidate.clone()) {
            return candidate;
        }
        n += 1;
    }
}

fn format_identifier(input: &str) -> String {
    let lowered;
    let input = if !input.is_empty()
        && input
            .chars()
            .all(|c| c == '_' || c.is_ascii_uppercase() || c.is_ascii_digit())
    {
        lowered = input.to_ascii_lowercase();
        &lowered
    } else {
        input
    };
    let mut result = String::new();
    for word in input
        .split(|c: char| !c.is_ascii_alphanumeric())
        .filter(|w| !w.is_empty())
    {
        result.push_str(&proper_word(word));
    }
    result.retain(|c| c.is_ascii_alphanumeric());
    if result.is_empty() {
        return "NAMINGFAILED".into();
    }
    if result.chars().all(|c| c.is_ascii_digit()) {
        return format!("Num{result}");
    }
    if let Some(digit) = result.chars().next().and_then(|c| c.to_digit(10)) {
        const WORDS: [&str; 10] =
            ["Zero", "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine"];
        result.replace_range(0..1, WORDS[digit as usize]);
    }
    result
}

fn proper_word(word: &str) -> String {
    let upper = word.to_ascii_uppercase();
    if INITIALISMS.contains(&upper.as_str()) {
        return upper;
    }
    // Preserve camel-case boundaries, while normalizing recognized suffix initialisms.
    let mut chars = word.chars();
    let mut out: String = chars.next().into_iter().flat_map(char::to_uppercase).collect();
    out.extend(chars);
    for initialism in INITIALISMS {
        if out.len() >= initialism.len()
            && out[out.len() - initialism.len()..].eq_ignore_ascii_case(initialism)
        {
            let start = out.len() - initialism.len();
            out.replace_range(start.., initialism);
            break;
        }
    }
    out
}

fn is_rfc3339_shape(s: &str) -> bool {
    let b = s.as_bytes();
    if b.len() < 20
        || b.get(4) != Some(&b'-')
        || b.get(7) != Some(&b'-')
        || b.get(10) != Some(&b'T')
        || b.get(13) != Some(&b':')
        || b.get(16) != Some(&b':')
    {
        return false;
    }
    s.ends_with('Z')
        || (b.len() >= 25
            && matches!(b.get(b.len() - 6), Some(b'+' | b'-'))
            && b.get(b.len() - 3) == Some(&b':'))
}

fn escape_tag(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn inline(json: &str) -> String {
        convert(json, &Options { flatten: false, ..Options::default() }).unwrap()
    }

    #[test]
    fn scalar_and_names() {
        assert_eq!(
            inline(r#"{"user_id":1,"PublicIP":"","active":true,"large":2147483647,"nil":null}"#),
            "type AutoGenerated struct {\n\tUserID int `json:\"user_id\"`\n\tPublicIP string `json:\"PublicIP\"`\n\tActive bool `json:\"active\"`\n\tLarge int64 `json:\"large\"`\n\tNil any `json:\"nil\"`\n}\n"
        );
    }

    #[test]
    fn nested_inline_and_arrays_merge() {
        assert_eq!(
            inline(r#"{"people":[{"name":"A","age":1},{"name":"B","email":"b"}]}"#),
            "type AutoGenerated struct {\n\tPeople []struct {\n\t\tName string `json:\"name\"`\n\t\tAge int `json:\"age,omitempty\"`\n\t\tEmail string `json:\"email,omitempty\"`\n\t} `json:\"people\"`\n}\n"
        );
    }

    #[test]
    fn array_type_reconciliation() {
        assert!(inline(r#"{"n":[1,2.5]}"#).contains("N []float64"));
        assert!(inline(r#"{"n":[1,"x"]}"#).contains("N []any"));
        assert!(inline(r#"{"n":[]}"#).contains("N []any"));
        assert!(inline(r#"{"n":1.00}"#).contains("N float64"));
    }

    #[test]
    fn flatten_and_examples() {
        let options = Options {
            flatten: true,
            example: true,
            all_omitempty: true,
            ..Options::default()
        };
        let got = convert(r#"{"profile":{"created":"2023-08-15T14:30:00Z"},"age":46}"#, &options)
            .unwrap();
        assert!(got.contains("Profile Profile `json:\"profile,omitempty\"`"));
        assert!(got.contains("type Profile struct"));
        assert!(got.contains("Created time.Time"));
        assert!(got.contains("example:\"46\""));
    }

    #[test]
    fn invalid_json_is_an_error() {
        assert!(convert("{", &Options::default()).is_err());
    }

    #[test]
    fn root_array_has_distinct_element_type_when_flattened() {
        let options = Options { flatten: true, ..Options::default() };
        let got = convert(r#"[{"id":1},{"id":2,"label":"two"}]"#, &options).unwrap();
        assert_eq!(
            got,
            "type AutoGenerated []AutoGeneratedItem\n\n\
             type AutoGeneratedItem struct {\n\
             \tID int `json:\"id\"`\n\
             \tLabel string `json:\"label,omitempty\"`\n\
             }\n"
        );
    }

    #[test]
    fn colliding_identifiers_are_made_unique() {
        let got = inline(r#"{"+1":"positive","-1":"negative","user-id":1,"user_id":2}"#);
        assert!(got.contains("Num1 string `json:\"+1\"`"));
        assert!(got.contains("Num10 string `json:\"-1\"`"));
        assert!(got.contains("UserID int `json:\"user-id\"`"));
        assert!(got.contains("UserID0 int `json:\"user_id\"`"));
    }

    #[test]
    fn custom_type_name_is_sanitized() {
        let options = Options {
            type_name: Some("api-response".into()),
            ..Options::default()
        };
        assert!(
            convert("{}", &options)
                .unwrap()
                .starts_with("type APIResponse struct")
        );
    }

    #[test]
    fn top_level_scalars_and_arrays_are_supported() {
        assert_eq!(inline("true"), "type AutoGenerated bool\n");
        assert_eq!(inline("[1,2147483647]"), "type AutoGenerated []int64\n");
    }
}
